
AD_connexion:
    path:   /testConnexion
    defaults: { _controller: NoxIntranetUserBundle:ADConnexion:ADConnexion }

AD_connexion_check:
    path:   /testConnexionCheck
    defaults: { _controller: NoxIntranetUserBundle:ADConnexion:ADConnexionCheck }
    
nox_intranet_developpement_professionnel_formulaire:
    path:   /developpement-professionnel-formulaire/{collaborateurUsername}
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:formulaireDeveloppementProfessionnel, collaborateurUsername: '' }
    
nox_intranet_developpement_professionnel_synthese_excel:
    path:   /developpement-professionnel-synthese-excel
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:exportToExcel }
    
nox_intranet_developpement_professionnel_download_pdf_export:
    path:   /developpement-professionnel-download-pdf-export/{fileName}
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:downloadPDFExport }
    
nox_intranet_developpement_professionnel_ajax_convert_html_to_pdf:
    path:   /developpement-professionnel-ajax-convert-html-to-pdf
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:ajaxConvertHtmlToPDF }
    
nox_intranet_developpement_professionnel_monitoring_formulaire:
    path:   administration/developpement-professionnel/monitoring-formulaire
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:formulaireMonitoring }
    
nox_intranet_developpement_professionnel_matrice_competence_formulaire:
    path:   /matrice-competence-formulaire
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:competenceForm }