
AD_connexion:
    path:   /testConnexion
    defaults: { _controller: NoxIntranetUserBundle:ADConnexion:ADConnexion }

AD_connexion_check:
    path:   /testConnexionCheck
    defaults: { _controller: NoxIntranetUserBundle:ADConnexion:ADConnexionCheck }
    
nox_intranet_developpement_professionnel_formulaire:
    path:   /developpement-professionnel-formulaire/{collaborateurUsername}
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:formulaireDeveloppementProfessionnel, collaborateurUsername: '' }
    
nox_intranet_developpement_professionnel_synthese_excel:
    path:   /developpement-professionnel-synthese-excel
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:exportToExcel }