
AD_connexion:
    path:   /testConnexion
    defaults: { _controller: NoxIntranetUserBundle:ADConnexion:ADConnexion }

AD_connexion_check:
    path:   /testConnexionCheck
    defaults: { _controller: NoxIntranetUserBundle:ADConnexion:ADConnexionCheck }
    
nox_intranet_developpement_professionnel_formulaire:
    path:   /developpement-professionnel-formulaire/{collaborateurUsername}
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:formulaireDeveloppementProfessionnel, collaborateurUsername: '' }
    
nox_intranet_developpement_professionnel_synthese_excel:
    path:   /developpement-professionnel-synthese-excel
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:exportToExcel }
    
nox_intranet_developpement_professionnel_download_pdf_export:
    path:   /developpement-professionnel-download-pdf-export/{fileName}
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:downloadPDFExport }
    
nox_intranet_developpement_professionnel_ajax_convert_html_to_pdf:
    path:   /developpement-professionnel-ajax-convert-html-to-pdf
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:ajaxConvertHtmlToPDF }
    
nox_intranet_developpement_professionnel_monitoring_formulaire:
    path:   administration/developpement-professionnel/monitoring-formulaire
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:formulaireMonitoring }
    
nox_intranet_developpement_professionnel_matrice_competence_formulaire:
    path:   /ressources/matrice-competence/mes-competences
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:competenceForm }
    
nox_intranet_developpement_professionnel_matrice_competence_edition_collaborateur:
    path:   /ressources/matrice-competence/edition-matrice-collaborateur/{userId}
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:collaborateurMatriceEditon }
    
nox_intranet_developpement_professionnel_matrice_competence_tableau:
    path:   /ressources/matrice-competence/competences-collaborateurs
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:matriceCompetenceTable }
    
nox_intranet_developpement_professionnel_matrice_competence_file_extraction:
    path:   /ressources/matrice-competence/file-extraction
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:extractMatriceCompetenceData }

nox_intranet_developpement_professionnel_gestion_entretien_professionnel:
    path:   /developpement-professionnel/gestion-entretien-professionnel
    defaults: { _controller: NoxIntranetUserBundle:DeveloppementProfessionnel\DeveloppementProfessionnel:gestionEntretienProfessionnelN2 }
    
nox_intranet_ajax_matrice_collaborateur_edition_save:
    path:   ressources/matrice-competence/ajax-collaborateur-edition-save
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:ajaxSaveMatriceCollaborateurEdition }
    
nox_intranet_ajax_matrice_collaborateur_get_matrice_collaborateur:
    path:   ressources/matrice-competence/ajax-get-matrice-collaborateur
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:ajaxGetMatriceCollaborateur }
    
nox_intranet_matrice_collaborateur_selection_collaborateur:
    path:   ressources/matrice-competence/selection-collaborateur
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:collaborateurSelection }
    
nox_intranet_matrice_collaborateur_ajax_search_in_matrice:
    path:   ressources/matrice-competence/ajax-search-in-matrice
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:ajaxSearchInMatrice }
    
nox_intranet_matrice_collaborateur_info_file_uploading:
    path:   ressources/matrice-competence/collaborateurs-info-file-uploading
    defaults: { _controller: NoxIntranetUserBundle:MatriceCompetence\MatriceCompetence:collaborateursInfoUploading }