services:
    activity_listener:
        class: NoxIntranet\UserBundle\Listener\ActivityListener
        arguments: [@security.context, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
    noxintranet_userbundle.updatematricecompetencefile:
        class: NoxIntranet\UserBundle\Controller\MatriceCompetence\UpdateMatriceCompetenceController
        arguments: ['@service_container', "@doctrine.orm.entity_manager"]
