<?php

namespace NoxIntranet\PDFParsingBundle\Entity;

/**
 * PDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PDFRepository extends \Doctrine\ORM\EntityRepository
{
}
