<?php

/* support/include/i18n/en_US/templates/email/ticket.reply.yaml */
class __TwigTemplate_e06ffe36250ed2b235dc62895f259c96b5c71c00813b5e425dcfca63a37e10ea extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_86debc0216f28b1e3589231580b4fdb7e003947483d8a98049b3a2798f5ac9cb = $this->env->getExtension("native_profiler");
        $__internal_86debc0216f28b1e3589231580b4fdb7e003947483d8a98049b3a2798f5ac9cb->enter($__internal_86debc0216f28b1e3589231580b4fdb7e003947483d8a98049b3a2798f5ac9cb_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "support/include/i18n/en_US/templates/email/ticket.reply.yaml"));

        // line 1
        echo "#
# Email template: ticket.reply.yaml
#
# Sent to users when a staff members makes a reply to their ticket. Replies
# are only generated by staff members.
#
---
notes: |
    Sent to users when a staff members makes a reply to their ticket.
    Replies are only generated by staff members.

subject: |
    Re: %{ticket.subject} [#%{ticket.number}]
body: |
    <h3><strong>Dear %{recipient.name},</strong></h3>
    %{response}
    <br>
    <br>
    <div style=\"color: rgb(127, 127, 127);\">
    Your %{company.name} Team,<br>
    %{signature}
    </div>
    <hr>
    <div style=\"color: rgb(127, 127, 127); font-size: small; text-align: center;\"
    ><em>We hope this response has sufficiently answered your questions. If
    not, please do not send another email. Instead, reply to this email or
    <a href=\"%{recipient.ticket_link}\" style=\"color: rgb(84, 141, 212);\" >login
    to your account</a> for a complete archive of all your support requests
    and responses.</em></div>
";
        
        $__internal_86debc0216f28b1e3589231580b4fdb7e003947483d8a98049b3a2798f5ac9cb->leave($__internal_86debc0216f28b1e3589231580b4fdb7e003947483d8a98049b3a2798f5ac9cb_prof);

    }

    public function getTemplateName()
    {
        return "support/include/i18n/en_US/templates/email/ticket.reply.yaml";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }
}
/* #*/
/* # Email template: ticket.reply.yaml*/
/* #*/
/* # Sent to users when a staff members makes a reply to their ticket. Replies*/
/* # are only generated by staff members.*/
/* #*/
/* ---*/
/* notes: |*/
/*     Sent to users when a staff members makes a reply to their ticket.*/
/*     Replies are only generated by staff members.*/
/* */
/* subject: |*/
/*     Re: %{ticket.subject} [#%{ticket.number}]*/
/* body: |*/
/*     <h3><strong>Dear %{recipient.name},</strong></h3>*/
/*     %{response}*/
/*     <br>*/
/*     <br>*/
/*     <div style="color: rgb(127, 127, 127);">*/
/*     Your %{company.name} Team,<br>*/
/*     %{signature}*/
/*     </div>*/
/*     <hr>*/
/*     <div style="color: rgb(127, 127, 127); font-size: small; text-align: center;"*/
/*     ><em>We hope this response has sufficiently answered your questions. If*/
/*     not, please do not send another email. Instead, reply to this email or*/
/*     <a href="%{recipient.ticket_link}" style="color: rgb(84, 141, 212);" >login*/
/*     to your account</a> for a complete archive of all your support requests*/
/*     and responses.</em></div>*/
/* */
