# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    intranet_version: v1.8
    

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    nox_intranet.twig_extension.encryptString:
        class: NoxIntranet\CommunicationBundle\Twig\Extension\EncryptStringExtension
        public: false
        tags:
            - { name: twig.extension }
    nox_intranet.error_listener:
        class: NoxIntranet\AdministrationBundle\Controller\ErrorHandler\ErrorListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: handleError }
