nox_intranet_accueil:
    path:     /accueil
    defaults: { _controller: NoxIntranetAccueilBundle:Accueil:majCommunication }
    
#nox_intranet_accesinterdit:
#    path:     /accesInterdit
#    defaults: { _controller: NoxIntranetAccueilBundle:Accueil:accesInterdit }
#    
#nox_intranet_connexionRequise:
#    path:     /connexionRequise
#    defaults: { _controller: NoxIntranetAccueilBundle:Accueil:connexionRequise }
    
nox_intranet_debug:
    path: /debug
    defaults: { _controller: NoxIntranetAccueilBundle:Accueil:debug }
    
nox_intranet_ajax_get_message_alerte:
    path: /accueil/get-message-alerte
    defaults: { _controller: NoxIntranetAccueilBundle:Accueil:ajaxGetMessageAlert }
    
nox_intranet_message_alerte:
    path: /accueil/message-alerte
    defaults: { _controller: NoxIntranetAccueilBundle:Accueil:messageAlerte }
    
nox_intranet_charte_informatique:
    path: /accueil/charte-informatique
    defaults: { _controller: NoxIntranetAccueilBundle:CharteInformatique:displayCharteInformatique }
    
nox_intranet_charte_informatique_monitoring:
    path: /administration/charte-informatique-monitoring
    defaults: { _controller: NoxIntranetAccueilBundle:CharteInformatique:monitoringCharteInformatique }
    
nox_intranet_charte_informatique_reset:
    path: /administration/charte-informatique-reset/{collaborateurUsername}
    defaults: { _controller: NoxIntranetAccueilBundle:CharteInformatique:resetCharteInformatiqueReading }
    