services:
    nox_intranet_accueil.compteur_vues.incrementation:
        class: NoxIntranet\AccueilBundle\CompteurVues\CompteurVuesIncrementation
        arguments: ['@doctrine.orm.entity_manager']
        
    nox_intranet_accueil.compteur_vues.listener:
        class: NoxIntranet\AccueilBundle\CompteurVues\CompteurVuesListener
        arguments: [@nox_intranet_accueil.compteur_vues.incrementation, '@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processCompteurVues }
