services:
    noxintranet_administration.majuserdb:
        class: NoxIntranet\AdministrationBundle\MajUserDB\NoxIntranetMajUserDB
        arguments: [ @doctrine.orm.entity_manager, '@service_container' ]