<?php

namespace NoxIntranet\AccueilBundle\Entity;

/**
 * AnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnoncesRepository extends \Doctrine\ORM\EntityRepository
{
}
