<?php

namespace NoxIntranet\AccueilBundle\Entity;

/**
 * MessageAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
