<?php

namespace Proxies\__CG__\NoxIntranet\RessourcesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Suivis extends \NoxIntranet\RessourcesBundle\Entity\Suivis implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'nom', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'agence', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'numeroGX', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'profil', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'statut', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'idModele', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'commune', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'marche', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'nocommande', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'noclient', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'objet', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'noINGEDIABEP', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'estimatif', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'noInterlocuteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'nom', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'agence', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'numeroGX', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'profil', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'statut', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'idModele', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'commune', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'marche', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'nocommande', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'noclient', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'objet', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'noINGEDIABEP', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'estimatif', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Suivis' . "\0" . 'noInterlocuteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Suivis $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgence($agence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgence', [$agence]);

        return parent::setAgence($agence);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgence', []);

        return parent::getAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfil($profil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfil', [$profil]);

        return parent::setProfil($profil);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfil', []);

        return parent::getProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdModele($idModele)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdModele', [$idModele]);

        return parent::setIdModele($idModele);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdModele()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdModele', []);

        return parent::getIdModele();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommune($commune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommune', [$commune]);

        return parent::setCommune($commune);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommune', []);

        return parent::getCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarche($marche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarche', [$marche]);

        return parent::setMarche($marche);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarche', []);

        return parent::getMarche();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoclient($noclient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoclient', [$noclient]);

        return parent::setNoclient($noclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoclient', []);

        return parent::getNoclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjet($objet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjet', [$objet]);

        return parent::setObjet($objet);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjet', []);

        return parent::getObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoINGEDIABEP($noINGEDIABEP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoINGEDIABEP', [$noINGEDIABEP]);

        return parent::setNoINGEDIABEP($noINGEDIABEP);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoINGEDIABEP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoINGEDIABEP', []);

        return parent::getNoINGEDIABEP();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstimatif($estimatif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstimatif', [$estimatif]);

        return parent::setEstimatif($estimatif);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimatif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimatif', []);

        return parent::getEstimatif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNocommande($nocommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNocommande', [$nocommande]);

        return parent::setNocommande($nocommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNocommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNocommande', []);

        return parent::getNocommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoInterlocuteur($noInterlocuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoInterlocuteur', [$noInterlocuteur]);

        return parent::setNoInterlocuteur($noInterlocuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoInterlocuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoInterlocuteur', []);

        return parent::getNoInterlocuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroGX($numeroGX)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroGX', [$numeroGX]);

        return parent::setNumeroGX($numeroGX);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroGX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroGX', []);

        return parent::getNumeroGX();
    }

}
