<?php

namespace Proxies\__CG__\NoxIntranet\RessourcesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proposition_Echanges extends \NoxIntranet\RessourcesBundle\Entity\Proposition_Echanges implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'cleDemande', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'da2', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'postDate', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'sender', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'message'];
        }

        return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'cleDemande', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'da2', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'postDate', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'sender', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\Proposition_Echanges' . "\0" . 'message'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proposition_Echanges $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCleDemande($cleDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCleDemande', [$cleDemande]);

        return parent::setCleDemande($cleDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCleDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCleDemande', []);

        return parent::getCleDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setDa2($da2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDa2', [$da2]);

        return parent::setDa2($da2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDa2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDa2', []);

        return parent::getDa2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDate($postDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDate', [$postDate]);

        return parent::setPostDate($postDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDate', []);

        return parent::getPostDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSender($sender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSender', [$sender]);

        return parent::setSender($sender);
    }

    /**
     * {@inheritDoc}
     */
    public function getSender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSender', []);

        return parent::getSender();
    }

}
