<?php

namespace Proxies\__CG__\NoxIntranet\RessourcesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RecherchePrestation extends \NoxIntranet\RessourcesBundle\Entity\RecherchePrestation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'libelle', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'lieuOperation', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'lieuPrestation', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'descriptif', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'deplacement', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'dateDemarrage', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'dateRendu', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'livrables', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'volumeSousTraitance', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'status', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'emailDA', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'DA1', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'demandeur', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'cleDemande', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'dateCreation'];
        }

        return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'libelle', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'lieuOperation', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'lieuPrestation', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'descriptif', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'deplacement', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'dateDemarrage', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'dateRendu', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'livrables', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'volumeSousTraitance', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'status', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'emailDA', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'DA1', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'demandeur', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'cleDemande', '' . "\0" . 'NoxIntranet\\RessourcesBundle\\Entity\\RecherchePrestation' . "\0" . 'dateCreation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RecherchePrestation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuOperation($lieuOperation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuOperation', [$lieuOperation]);

        return parent::setLieuOperation($lieuOperation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuOperation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuOperation', []);

        return parent::getLieuOperation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuPrestation($lieuPrestation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuPrestation', [$lieuPrestation]);

        return parent::setLieuPrestation($lieuPrestation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuPrestation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuPrestation', []);

        return parent::getLieuPrestation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeplacement($deplacement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeplacement', [$deplacement]);

        return parent::setDeplacement($deplacement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeplacement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeplacement', []);

        return parent::getDeplacement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDemarrage($dateDemarrage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDemarrage', [$dateDemarrage]);

        return parent::setDateDemarrage($dateDemarrage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDemarrage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDemarrage', []);

        return parent::getDateDemarrage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRendu($dateRendu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRendu', [$dateRendu]);

        return parent::setDateRendu($dateRendu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRendu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRendu', []);

        return parent::getDateRendu();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolumeSousTraitance($volumeSousTraitance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolumeSousTraitance', [$volumeSousTraitance]);

        return parent::setVolumeSousTraitance($volumeSousTraitance);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolumeSousTraitance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolumeSousTraitance', []);

        return parent::getVolumeSousTraitance();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailDA($emailDA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailDA', [$emailDA]);

        return parent::setEmailDA($emailDA);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailDA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailDA', []);

        return parent::getEmailDA();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeur($demandeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeur', [$demandeur]);

        return parent::setDemandeur($demandeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeur', []);

        return parent::getDemandeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCleDemande($cleDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCleDemande', [$cleDemande]);

        return parent::setCleDemande($cleDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCleDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCleDemande', []);

        return parent::getCleDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setDA1($dA1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDA1', [$dA1]);

        return parent::setDA1($dA1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDA1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDA1', []);

        return parent::getDA1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptif($descriptif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptif', [$descriptif]);

        return parent::setDescriptif($descriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptif', []);

        return parent::getDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivrables($livrables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivrables', [$livrables]);

        return parent::setLivrables($livrables);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivrables()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivrables', []);

        return parent::getLivrables();
    }

}
