<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * AA_Client_AdrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AA_Client_AdrRepository extends \Doctrine\ORM\EntityRepository
{
}
