<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * AA_ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AA_ClientRepository extends \Doctrine\ORM\EntityRepository
{
}
