<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * AA_ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AA_ContactRepository extends \Doctrine\ORM\EntityRepository
{
}
