<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * demandeRecrutementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeRecrutementRepository extends \Doctrine\ORM\EntityRepository
{
}
