<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * DonneesSuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesSuiviRepository extends \Doctrine\ORM\EntityRepository
{
}
