<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * ImprimantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImprimantesRepository extends \Doctrine\ORM\EntityRepository
{
}
