<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * LiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiensRepository extends \Doctrine\ORM\EntityRepository
{
}
