<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * PrestationDARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationDARepository extends \Doctrine\ORM\EntityRepository
{
}
