<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * ProfilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilsRepository extends \Doctrine\ORM\EntityRepository
{
}
