<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * PropositionPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropositionPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
