<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * Proposition_EchangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Proposition_EchangesRepository extends \Doctrine\ORM\EntityRepository
{
}
