<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * RecherchePrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecherchePrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
