<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * ReferencesKeywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferencesKeywordsRepository extends \Doctrine\ORM\EntityRepository
{
}
