<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * ServeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServeurRepository extends \Doctrine\ORM\EntityRepository
{
}
