<?php

namespace NoxIntranet\RessourcesBundle\Entity;

/**
 * SuivisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuivisRepository extends \Doctrine\ORM\EntityRepository
{
}
