<?php

namespace NoxIntranet\UserBundle\Entity;

/**
 * DeveloppementProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloppementProfessionnelRepository extends \Doctrine\ORM\EntityRepository
{
}
