<?php

namespace NoxIntranet\UserBundle\Entity;

/**
 * MatriceCompetenceConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceCompetenceConsultationRepository extends \Doctrine\ORM\EntityRepository
{
}
