<?php

namespace NoxIntranet\UserBundle\Entity;

/**
 * MatriceCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
