<?php

namespace NoxIntranet\UserBundle\Entity;

/**
 * MatriceCompetenceEditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceCompetenceEditionRepository extends \Doctrine\ORM\EntityRepository
{
}
