<?php

namespace NoxIntranet\UserBundle\Entity;

/**
 * RecrutementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementRepository extends \Doctrine\ORM\EntityRepository
{
}
