<?php

namespace NoxIntranet\UserBundle\Entity;

/**
 * User_Info_IntranetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_Info_IntranetRepository extends \Doctrine\ORM\EntityRepository
{
}
