<?php

namespace NoxIntranet\SatisfactionClientBundle\Entity;

/**
 * FicheEvaluationSTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheEvaluationSTRepository extends \Doctrine\ORM\EntityRepository
{
}
