<?php

namespace NoxIntranet\SatisfactionClientBundle\Entity;

/**
 * InfoEffectuerFicheEvaluationSTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEffectuerFicheEvaluationSTRepository extends \Doctrine\ORM\EntityRepository
{
}
