<?php

namespace NoxIntranet\SatisfactionClientBundle\Entity;

/**
 * InfoEnvoiQuestionnaireSatisfactionClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEnvoiQuestionnaireSatisfactionClientRepository extends \Doctrine\ORM\EntityRepository
{
}
