services:
#    nox_intranet_news.example:
#        class: NoxIntranet\NewsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    nox_intranet.twig_extension:
        class: NoxIntranet\CommunicationBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
