<?php 
/* This is an autogenerated phplicensewatcher config-file */
/* A good commented config-file (sample-config.php) is included in the distribution (in case you want to modify it manually). */
$lmutil_loc="./lmutil";
$i4blt_loc="/opt/lum/ls/bin/i4blt";
$LUM_timeout=4;
$notify_address="wolfgang.dautermann@fh-joanneum.at";
$lead_time=10;
$disable_autorefresh=0;
$disable_license_removal=0;
$collection_interval=15;
$db_type="mysql";
$db_hostname="localhost";
$db_username="intranetadmin";
$db_password="intranet";
$db_database="licenses";
$dsn="mysql://intranetadmin:intranet@localhost/licenses";
$colors="#ffffdd,#ff9966, #ffffaa,#ccccff,#cccccc,#ffcc66,#99ff99,#eeeeee,#66ffff,#ccffff, #ffff66, #ffccff,#ff66ff, yellow,lightgreen,lightblue";
$smallgraph="300,200";
$largegraph="600,300";
$legendpoints="";
$servers[]="192.168.35.14";
$description[]="Licences Nox";
$log_file[]="";
$servers[]="31414@FZT-Lamborghini.fh-joanneum.at";
$description[]="STAR CD";
$log_file[]="";
$lmstat_loc=$lmutil_loc . " lmstat"; 
?>
