<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * AffairesGXRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffairesGXRepository extends \Doctrine\ORM\EntityRepository
{
}
