<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * JustificatifTransportFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificatifTransportFileRepository extends \Doctrine\ORM\EntityRepository
{
}
