<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * JustificatifFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificatifFileRepository extends \Doctrine\ORM\EntityRepository
{
}
