<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * JustificatifSupplementairesCompilationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificatifSupplementairesCompilationRepository extends \Doctrine\ORM\EntityRepository
{
}
