<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * PointageValideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageValideRepository extends \Doctrine\ORM\EntityRepository
{
}
