<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * TableauCompilationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableauCompilationRepository extends \Doctrine\ORM\EntityRepository
{
}
