<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * TableauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableauRepository extends \Doctrine\ORM\EntityRepository
{
}
