<?php

namespace NoxIntranet\PointageBundle\Entity;

/**
 * UsersHierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersHierarchyRepository extends \Doctrine\ORM\EntityRepository
{
}
