<?php

/* support/include/i18n/en_US/templates/email/ticket.reply.yaml */
class __TwigTemplate_3514fe4328e4f248d07f385590bfffe787c2d2e63f7012b285b4015da89593d7 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        echo "#
# Email template: ticket.reply.yaml
#
# Sent to users when a staff members makes a reply to their ticket. Replies
# are only generated by staff members.
#
---
notes: |
    Sent to users when a staff members makes a reply to their ticket.
    Replies are only generated by staff members.

subject: |
    Re: %{ticket.subject} [#%{ticket.number}]
body: |
    <h3><strong>Dear %{recipient.name},</strong></h3>
    %{response}
    <br>
    <br>
    <div style=\"color: rgb(127, 127, 127);\">
    Your %{company.name} Team,<br>
    %{signature}
    </div>
    <hr>
    <div style=\"color: rgb(127, 127, 127); font-size: small; text-align: center;\"
    ><em>We hope this response has sufficiently answered your questions. If
    not, please do not send another email. Instead, reply to this email or
    <a href=\"%{recipient.ticket_link}\" style=\"color: rgb(84, 141, 212);\" >login
    to your account</a> for a complete archive of all your support requests
    and responses.</em></div>
";
    }

    public function getTemplateName()
    {
        return "support/include/i18n/en_US/templates/email/ticket.reply.yaml";
    }

    public function getDebugInfo()
    {
        return array (  19 => 1,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this->getSourceContext()->getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("", "support/include/i18n/en_US/templates/email/ticket.reply.yaml", "C:\\wamp\\www\\Symfony\\app\\Resources\\views\\support\\include\\i18n\\en_US\\templates\\email\\ticket.reply.yaml");
    }
}
