nox_intranet_support_si:
    path:     /supportSI
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:accueil }

nox_intranet_support_licenses:
    path:     /supportSI/licenses
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:licenses }
    
nox_intranet_support_ticketing:
    path:     /supportSI/ticketing
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:ticketing }
    
nox_intranet_support_wiki:
    path:     /supportSI/wiki
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:wiki }
    
nox_intranet_demande_materiel:
    path: /supportSI/demande-materiel-logiciel
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:demande }  
    
nox_intranet_demande_materiel_confirmation_dsi:
    path: /supportSI/confirmation-demande-dsi/{cleDemande}
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:demandeConfirmationDSI }
    
nox_intranet_demande_materiel_confirmation_superieur_hierarchique:
    path: /supportSI/confirmation-demande-superieur-hierarchique/{cleDemande}/{reponse}
    defaults: { _controller: NoxIntranetSupportSIBundle:SupportSI:demandeConfirmationSuperieurHierarchique }
    
nox_intranet_avancement_projet:
    path: /supportSI/avancementProjet
    defaults: { _controller: NoxIntranetSupportSIBundle:AvancementProjet:avancementProjet }
    
nox_intranet_information:
   path: /supportSI/information
   defaults: { _controller: NoxIntranetSupportSIBundle:Information:information }