services:
#    nox_intranet_support_si.example:
#        class: NoxIntranet\SupportSIBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    nox_intranet_support_si.demande_materiel_revival:
        class: NoxIntranet\SupportSIBundle\Controller\DemandeMateriel\DemandeMaterielRevival
        arguments: [@doctrine.orm.entity_manager]
