<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * Donnees_ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Donnees_ClientRepository extends \Doctrine\ORM\EntityRepository
{
}
