<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * Donnees_InterlocuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Donnees_InterlocuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
