<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * DonneesFormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesFormulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
