<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * FormulairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulairesRepository extends \Doctrine\ORM\EntityRepository
{
}
