<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * HelpdeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpdeskRepository extends \Doctrine\ORM\EntityRepository
{
}
