<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * LiaisonSuiviChampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiaisonSuiviChampRepository extends \Doctrine\ORM\EntityRepository
{
}
