<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * MAJAutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MAJAutoRepository extends \Doctrine\ORM\EntityRepository
{
}
