<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * ScriptMonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptMonitoringRepository extends \Doctrine\ORM\EntityRepository
{
}
