<?php

namespace NoxIntranet\AdministrationBundle\Entity;

/**
 * texteEncartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class texteEncartRepository extends \Doctrine\ORM\EntityRepository
{
}
