nox_intranet_pointage:
    path:     /ressources/pointage
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:accueil }
    
nox_intranet_pointage_ajax_set_date:
    path:     /ressources/pointage-ajax-set-date
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:ajaxSetDate}
    
nox_intranet_pointage_ajax_save_data:
    path:     /ressources/pointage-ajax-save-data
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:ajaxSaveData}
    
nox_intranet_pointage_ajax_get_data:
    path:     /ressources/pointage-ajax-get-data
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:ajaxGetData}
    
nox_intranet_pointage_administratif:
    path:     /ressources/pointage-administratif
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:acceuilAdministratif }
    
nox_intranet_pointage_administratif_ajax_get_data:
    path:     /ressources/pointage-administratif-ajax-get-data
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:ajaxGetDataAdministratif }
    
nox_intranet_gestion_pointage:
    path:   /ressources/gestion-pointage
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:gestionPointage }
    
nox_intranet_ajax_get_month_by_username:
    path:   /ressources/ajax-get-month-by-username
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:ajaxGetMonthByUser }
   
nox_intranet_ajax_get_year_by_month_and_username:
    path:   /ressources/ajax-get-year-by-month-and-username
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:ajaxGetYearByMonthAndUser }