nox_intranet_pointage:
    path:     /ressources/rh/pointage
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:accueil }
    
nox_intranet_pointage_ajax_set_date:
    path:     /ressources/pointage-ajax-set-date
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxSetDate}
    
nox_intranet_pointage_ajax_save_data:
    path:     /ressources/pointage-ajax-save-data
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxSaveData}
    
nox_intranet_pointage_ajax_get_data:
    path:     /ressources/pointage-ajax-get-data
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetData}
    
nox_intranet_pointage_administratif:
    path:     /ressources/pointage-administratif
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:acceuilAdministratif }
    
nox_intranet_pointage_administratif_ajax_get_data:
    path:     /ressources/pointage-administratif-ajax-get-data
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetDataAdministratif }
    
nox_intranet_assistantes_agence_gestion_pointage:
    path:   /ressources/assistantes-agence-gestion-pointages
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:assistantesAgenceGestionPointage }
    
nox_intranet_ajax_get_month_by_username:
    path:   /ressources/ajax-get-month-by-username
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetMonthByUser }
   
nox_intranet_ajax_get_year_by_month_and_username:
    path:   /ressources/ajax-get-year-by-month-and-username
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetYearByMonthAndUser }
    
nox_intranet_ajax_get_users_by_username:
    path:   /ressources/ajax-get-users-by-username
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetUsersByUsername }
    
nox_intranet_pointage_ajax_get_data_by_username:
    path:     /ressources/pointage-ajax-get-data-by-username
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetDataByUsername }
    
nox_intranet_pointage_ajax_get_status:
    path:     /ressources/pointage-ajax-get-status
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetPointageStatus }
    
nox_intranet_pointage_ajax_set_date_by_pointage_number:
    path:     /ressources/pointage-ajax-set-date-by-pointage-number
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxSetDateByPointageNumber}
    
nox_intranet_pointage_ajax_assistante_agence_validation:
    path:     /ressources/pointage-ajax-assistante-agence-validation
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxAssistanteValidation}
    
nox_intranet_assistantes_agence_pointage_compilation:
    path:     /ressources/assistantes-agence-pointages-compilation
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:assistantesAgencePointagesCompilation}
    
nox_intranet_pointage_ajax_get_assistantes_agence_pointage_compilation_by_month_and_year:
    path:   /ressources/ajax-get-assistantes-agence-pointage-compilation-by-month-and-year
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetAssistanceAgencePointageCompilationByMonthAndYear }
    
nox_intranet_ajax_save_compilation_data:
    path:   /ressources/ajax-save-compilation-data
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxSaveCompilationData }
    
nox_intranet_ajax_save_compilation_absences:
    path:   /ressources/ajax-save-compilation-absences
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxSaveCompilationAbsences }
    
nox_intranet_da_manager_pointage_compilation:
    path:     /ressources/da-manager-pointages-compilation
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:DAManagerPointagesCompilation}
    
nox_intranet_pointage_ajax_get_da_manager_pointage_compilation_by_month_and_year:
    path:   /ressources/ajax-get-da-manager-pointage-compilation-by-month-and-year
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetDAManagerPointageCompilationByMonthAndYear }
    
nox_intranet_assistantes_rh_pointage_compilation:
    path:     /ressources/assistantes-rh-pointages-compilation
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:assistantesRHPointagesCompilation}
    
nox_intranet_pointage_ajax_get_assistantes_rh_pointage_compilation_by_month_and_year:
    path:   /ressources/ajax-get-assistantes-rh-pointage-compilation-by-month-and-year
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetAssistantesRHPointageCompilationByMonthAndYear }
    
nox_intranet_pointage_compilation_ajax_get_status:
    path:     /ressources/pointage-compilation-ajax-get-status
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetPointageCompilationStatus }
    
nox_intranet_pointage_get_affaires_by_number:
    path:     /ressources/pointage-get-affaires-by-number
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetAffairesByNumber }
    
nox_intranet_affichage_compilation_valide:
    path:     /ressources/affichage-compilations-valides
    defaults: { _controller: NoxIntranetPointageBundle:Pointage:compilationValides}
    
nox_intranet_pointage_ajax_get_compilation_valide_by_month_and_year:
    path:   /ressources/ajax-get-compilations-valides-by-month-and-year
    defaults: { _controller: NoxIntranetPointageBundle:PointageAjax:ajaxGetCompilationsValideByMonthAndYear }