<?php

namespace Proxies\__CG__\NoxIntranet\PDFParsingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PDF extends \NoxIntranet\PDFParsingBundle\Entity\PDF implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'chemin', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'lien', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'nom', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'title', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'author', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'subject', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'keywords', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'pages', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'dateEnvoi'];
        }

        return ['__isInitialized__', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'id', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'chemin', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'lien', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'nom', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'title', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'author', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'subject', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'keywords', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'pages', '' . "\0" . 'NoxIntranet\\PDFParsingBundle\\Entity\\PDF' . "\0" . 'dateEnvoi'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PDF $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setChemin($chemin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChemin', [$chemin]);

        return parent::setChemin($chemin);
    }

    /**
     * {@inheritDoc}
     */
    public function getChemin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChemin', []);

        return parent::getChemin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords($keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', [$keywords]);

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', []);

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setPages($pages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPages', [$pages]);

        return parent::setPages($pages);
    }

    /**
     * {@inheritDoc}
     */
    public function getPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPages', []);

        return parent::getPages();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEnvoi($dateEnvoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEnvoi', [$dateEnvoi]);

        return parent::setDateEnvoi($dateEnvoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEnvoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEnvoi', []);

        return parent::getDateEnvoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setLien($lien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLien', [$lien]);

        return parent::setLien($lien);
    }

    /**
     * {@inheritDoc}
     */
    public function getLien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLien', []);

        return parent::getLien();
    }

}
