<?php

namespace NoxIntranet\SupportSIBundle\Entity;

/**
 * CompteurDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteurDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
