<?php

namespace NoxIntranet\SupportSIBundle\Entity;

/**
 * DemandeMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeMaterielRepository extends \Doctrine\ORM\EntityRepository
{
}
